[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "templar"
version = "0.1.0"
description = "Incentivized Foundation Model Training"
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.11"
authors = [
  { name = "const", email = "dont.email.me@gmail.com" }
]

dependencies = [
    "aiohttp==3.10.2",
    "bittensor==7.4.0",
    "substrate-interface",
    "boto3==1.34.131",
    "safetensors==0.4.5",
    "torch>=2.4.0",
    "transformers==4.44.2",
    "python-dotenv==1.0.1",
    "datasets==3.0.0",
    "torchvision==0.19.1",
    "wandb>=0.18.3",
    "typer==0.12.5",
    "numpy==1.26",
    "aioboto3>=13.1.1",
    "loguru==0.7.2",
    "uvloop==0.20.0",
    "aiofiles>=24.1.0",
    "random2",
    "pydantic>=2.9.2",
]

[tool.uv]
dev-dependencies = [
    "pytest>=8.3.3",
    "ruff>=0.8.1",
]

[project.urls]
Homepage = "https://github.com/raofoundation/templar"

[tool.setuptools.packages.find]
where = ["src"]

